name: sapiens
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pymc>=4
  - arviz[all]
  - numpy  
  - seaborn
  - pandas
  - matplotlib    
  - scipy
  - scikit-learn        
  - pip
    